# run application tests with vitest
name: Vitest

on:
  push:
    branches:
      - main
      - dev

jobs:
  vitest:
    name: Vitest tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # install dependencies with npm
      - name: Install dependencies
        run: npm install

      # vitest process
      - name: Run Vitest
        run: npx vitest run
